"""conversations

Revision ID: 886da68b44e0
Revises: 4999e290e323
Create Date: 2026-09-26 21:06:29.431021

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "886da68b44e0"
down_revision: str | Sequence[str] | None = "4999e290e323"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(length=32), nullable=False),
        sa.Column("customer_name", sa.String(length=128), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("topic", sa.String(length=64), nullable=True),
        sa.Column("case_id", sa.String(length=16), nullable=True),
        sa.Column("pending_handoff", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"], ["support_cases.id"], name=op.f("fk_conversations_case_id_support_cases")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_conversations_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_conversations_started_at"), ["started_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversations_started_at"))
        batch_op.drop_index(batch_op.f("ix_conversations_account_id"))

    op.drop_table("conversations")
    # ### end Alembic commands ###
