"""support cases, readings and resolutions

Revision ID: ee096bacd98b
Revises:
Create Date: 2026-09-26 18:47:54.643649

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee096bacd98b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resolution_answers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(length=32), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resolution_answers")),
    )
    with op.batch_alter_table("resolution_answers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_resolution_answers_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_resolution_answers_conversation_id"), ["conversation_id"], unique=False
        )

    op.create_table(
        "support_cases",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("account_id", sa.String(length=32), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("priority", sa.String(length=32), nullable=False),
        sa.Column("sla_days", sa.Integer(), nullable=False),
        sa.Column("queue", sa.String(length=64), nullable=False),
        sa.Column("expected_response_by", sa.Date(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("outcome", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "priority IN ('high', 'mid', 'low')", name=op.f("ck_support_cases_priority")
        ),
        sa.CheckConstraint(
            "status IN ('open', 'closed')", name=op.f("ck_support_cases_case_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_support_cases")),
    )
    with op.batch_alter_table("support_cases", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_support_cases_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_support_cases_status"), ["status"], unique=False)

    op.create_table(
        "case_conversations",
        sa.Column("case_id", sa.String(length=16), nullable=False),
        sa.Column("conversation_id", sa.String(length=64), nullable=False),
        sa.Column("linked_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["support_cases.id"],
            name=op.f("fk_case_conversations_case_id_support_cases"),
        ),
        sa.PrimaryKeyConstraint("case_id", "conversation_id", name=op.f("pk_case_conversations")),
    )
    with op.batch_alter_table("case_conversations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_case_conversations_conversation_id"), ["conversation_id"], unique=False
        )

    op.create_table(
        "customer_readings",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("account_id", sa.String(length=32), nullable=False),
        sa.Column("case_id", sa.String(length=16), nullable=False),
        sa.Column("conversation_id", sa.String(length=64), nullable=False),
        sa.Column("service", sa.String(length=32), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("read_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "service IN ('electricity', 'water')", name=op.f("ck_customer_readings_service")
        ),
        sa.CheckConstraint(
            "status IN ('awaiting_review')", name=op.f("ck_customer_readings_reading_status")
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["support_cases.id"],
            name=op.f("fk_customer_readings_case_id_support_cases"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_readings")),
    )
    with op.batch_alter_table("customer_readings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_customer_readings_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_customer_readings_case_id"), ["case_id"], unique=False)

    op.create_table(
        "held_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.String(length=16), nullable=False),
        sa.Column("conversation_id", sa.String(length=64), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"], ["support_cases.id"], name=op.f("fk_held_messages_case_id_support_cases")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_held_messages")),
    )
    with op.batch_alter_table("held_messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_held_messages_case_id"), ["case_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("held_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_held_messages_case_id"))

    op.drop_table("held_messages")
    with op.batch_alter_table("customer_readings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_customer_readings_case_id"))
        batch_op.drop_index(batch_op.f("ix_customer_readings_account_id"))

    op.drop_table("customer_readings")
    with op.batch_alter_table("case_conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_case_conversations_conversation_id"))

    op.drop_table("case_conversations")
    with op.batch_alter_table("support_cases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_support_cases_status"))
        batch_op.drop_index(batch_op.f("ix_support_cases_account_id"))

    op.drop_table("support_cases")
    with op.batch_alter_table("resolution_answers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resolution_answers_conversation_id"))
        batch_op.drop_index(batch_op.f("ix_resolution_answers_account_id"))

    op.drop_table("resolution_answers")
    # ### end Alembic commands ###
