"""agent desk case fields feedback and timeline

Revision ID: 2f551f4494e0
Revises: 886da68b44e0
Create Date: 2026-09-26 21:10:48.016105

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f551f4494e0"
down_revision: str | Sequence[str] | None = "886da68b44e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


OLD_CATEGORIES = {
    "Supply fault - repair needed": "Supply",
    "Meter fault": "Meter reading",
    "Meter reading review": "Meter reading",
    "Billing - estimated read": "Billing",
    "Billing - dispute or refund": "Billing",
    "Billing - payment arrangement": "Payments",
    "General enquiry": "Service",
}


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback_notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.String(length=16), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("author", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"], ["support_cases.id"], name=op.f("fk_feedback_notes_case_id_support_cases")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback_notes")),
    )
    with op.batch_alter_table("feedback_notes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_feedback_notes_case_id"), ["case_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_feedback_notes_created_at"), ["created_at"], unique=False
        )

    op.create_table(
        "timeline_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.String(length=16), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("label", sa.String(length=256), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"], ["support_cases.id"], name=op.f("fk_timeline_events_case_id_support_cases")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_timeline_events")),
    )
    with op.batch_alter_table("timeline_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_timeline_events_case_id"), ["case_id"], unique=False)

    # Existing rows are chat cases handed off by the AI Assistant.
    with op.batch_alter_table("support_cases", schema=None) as batch_op:
        batch_op.drop_constraint(op.f("ck_support_cases_case_status"), type_="check")
        batch_op.add_column(
            sa.Column("customer_name", sa.String(length=128), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column("region", sa.String(length=32), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column("vulnerable", sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(
            sa.Column("channel", sa.String(length=32), nullable=False, server_default="chat")
        )
        batch_op.add_column(
            sa.Column("source", sa.String(length=32), nullable=False, server_default="assistant")
        )
        batch_op.add_column(
            sa.Column("subject", sa.String(length=128), nullable=False, server_default="")
        )
        batch_op.add_column(sa.Column("description", sa.Text(), nullable=False, server_default=""))
        batch_op.add_column(sa.Column("disputed_amount", sa.Double(), nullable=True))
        batch_op.add_column(
            sa.Column("transfers", sa.Integer(), nullable=False, server_default="0")
        )
        batch_op.add_column(
            sa.Column("reopened", sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(sa.Column("assignee", sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column("priority_override", sa.String(length=32), nullable=True))
    # Cases opened before the desk's six categories (#34) used our old routing categories.
    for old, new in OLD_CATEGORIES.items():
        op.execute(
            sa.text("UPDATE support_cases SET category = :new WHERE category = :old").bindparams(
                old=old, new=new
            )
        )
    # Give existing cases the "opened" entry new cases get, so their History tab isn't empty.
    op.execute(
        "INSERT INTO timeline_events (case_id, at, label, actor) "
        "SELECT id, created_at, 'Opened (chat)', 'AI Assistant' FROM support_cases"
    )
    # The desk's Case Statuses: open → new, closed → resolved.
    op.execute("UPDATE support_cases SET status = 'new' WHERE status = 'open'")
    op.execute("UPDATE support_cases SET status = 'resolved' WHERE status = 'closed'")
    with op.batch_alter_table("support_cases", schema=None) as batch_op:
        batch_op.create_check_constraint(
            op.f("ck_support_cases_case_status"),
            "status IN ('new', 'in_progress', 'waiting_customer', 'resolved')",
        )
        batch_op.create_check_constraint(
            op.f("ck_support_cases_channel"),
            "channel IN ('chat', 'phone', 'email', 'web', 'letter')",
        )
        batch_op.create_check_constraint(
            op.f("ck_support_cases_case_source"), "source IN ('direct', 'assistant')"
        )
        batch_op.create_check_constraint(
            op.f("ck_support_cases_priority_override"), "priority_override IN ('P1', 'P2', 'P3')"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # The category mapping is lossy, so categories stay as the desk's six.
    with op.batch_alter_table("support_cases", schema=None) as batch_op:
        for name in ("case_status", "channel", "case_source", "priority_override"):
            batch_op.drop_constraint(op.f(f"ck_support_cases_{name}"), type_="check")
    op.execute("UPDATE support_cases SET status = 'closed' WHERE status = 'resolved'")
    op.execute("UPDATE support_cases SET status = 'open' WHERE status <> 'closed'")
    with op.batch_alter_table("support_cases", schema=None) as batch_op:
        for column in (
            "priority_override", "assignee", "reopened", "transfers", "disputed_amount",
            "description", "subject", "source", "channel", "vulnerable", "region", "customer_name",
        ):  # fmt: skip
            batch_op.drop_column(column)
        batch_op.create_check_constraint(
            op.f("ck_support_cases_case_status"), "status IN ('open', 'closed')"
        )
    with op.batch_alter_table("timeline_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_timeline_events_case_id"))
    op.drop_table("timeline_events")
    with op.batch_alter_table("feedback_notes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feedback_notes_created_at"))
        batch_op.drop_index(batch_op.f("ix_feedback_notes_case_id"))
    op.drop_table("feedback_notes")
