"""seed extras

Revision ID: 764cf52512c4
Revises: 2f551f4494e0
Create Date: 2026-09-26 21:18:46.383796

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "764cf52512c4"
down_revision: str | Sequence[str] | None = "2f551f4494e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "seed_extras",
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("record_id", sa.String(length=64), nullable=False),
        sa.Column("transcript", sa.JSON(), nullable=True),
        sa.Column("account", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("kind", "record_id", name=op.f("pk_seed_extras")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("seed_extras")
    # ### end Alembic commands ###
